/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentCoordinatorRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.People.Donor;
import Business.People.DonorRequest;
import Business.People.PatientRequest;
import java.awt.Color;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akshay
 */
public class VolunteerDonorRequestJPanel extends javax.swing.JPanel {

  private  EcoSystem system;
  private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
  //private DonorRequest donorRequest;
  
    VolunteerDonorRequestJPanel(EcoSystem system) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.system = system;
        populateRequestTable();
        
        
        
    }
   
     
       private void populateRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel) requestTable.getModel();
        
        dtm.setRowCount(0);
        
        
          for(DonorRequest dnr : system.getDonorRequestDirectory().getDonorRequestList()){
            System.out.println("PRINITNG IT HERE in Volunteer !!");
            System.out.println(dnr.getName());
        }
        
        
         for(DonorRequest donorRequest: system.getDonorRequestDirectory().getDonorRequestList()){            
            Object row[] = new Object[4];
            row[0]= donorRequest;
            row[1]= donorRequest.getName();
            row[2]= donorRequest.getContact();
            row[3]= donorRequest.getStatus();
              
            dtm.addRow(row);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        buttonApprove = new javax.swing.JButton();
        buttonReject = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        uidText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        genderText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        streetText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblProfilePicture = new javax.swing.JLabel();
        curedText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bloodText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        diagnosedDateText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        zipText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        contactText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lastDaySymptomsText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        buttonDetails = new javax.swing.JButton();
        dobText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        statusText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lastDonationText = new javax.swing.JTextField();
        labConfirmationText = new javax.swing.JTextField();
        followUpTestText = new javax.swing.JTextField();
        symptomsText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(73, 128, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTable.setBackground(new java.awt.Color(0, 0, 0));
        requestTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        requestTable.setForeground(new java.awt.Color(255, 255, 255));
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UID", "Name", "Contact", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 100));

        buttonApprove.setText("Approve");
        buttonApprove.setEnabled(false);
        buttonApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApproveActionPerformed(evt);
            }
        });
        add(buttonApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        buttonReject.setText("Reject");
        buttonReject.setEnabled(false);
        buttonReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRejectActionPerformed(evt);
            }
        });
        add(buttonReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 80, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        uidText.setBackground(new java.awt.Color(0, 0, 0));
        uidText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        uidText.setForeground(new java.awt.Color(255, 255, 255));
        add(uidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 118, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DOB");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Age");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        ageText.setBackground(new java.awt.Color(0, 0, 0));
        ageText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ageText.setForeground(new java.awt.Color(255, 255, 255));
        add(ageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 118, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        genderText.setBackground(new java.awt.Color(0, 0, 0));
        genderText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        genderText.setForeground(new java.awt.Color(255, 255, 255));
        add(genderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 118, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Blood group");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        streetText.setBackground(new java.awt.Color(0, 0, 0));
        streetText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        streetText.setForeground(new java.awt.Color(255, 255, 255));
        add(streetText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 176, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Covid diagnosed date");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        lblProfilePicture.setText("Photo Label");
        add(lblProfilePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 115, 90));

        curedText.setBackground(new java.awt.Color(0, 0, 0));
        curedText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        curedText.setForeground(new java.awt.Color(255, 255, 255));
        add(curedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 71, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Covid cured date");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        bloodText.setBackground(new java.awt.Color(0, 0, 0));
        bloodText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bloodText.setForeground(new java.awt.Color(255, 255, 255));
        add(bloodText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 122, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Street address");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        diagnosedDateText.setBackground(new java.awt.Color(0, 0, 0));
        diagnosedDateText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        diagnosedDateText.setForeground(new java.awt.Color(255, 255, 255));
        add(diagnosedDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 69, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("City");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        cityText.setBackground(new java.awt.Color(0, 0, 0));
        cityText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cityText.setForeground(new java.awt.Color(255, 255, 255));
        add(cityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 66, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("State");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, -1));

        stateText.setBackground(new java.awt.Color(0, 0, 0));
        stateText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        stateText.setForeground(new java.awt.Color(255, 255, 255));
        add(stateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 54, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ZipCode");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, -1));

        zipText.setBackground(new java.awt.Color(0, 0, 0));
        zipText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        zipText.setForeground(new java.awt.Color(255, 255, 255));
        add(zipText, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 103, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Contact Number");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        contactText.setBackground(new java.awt.Color(0, 0, 0));
        contactText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contactText.setForeground(new java.awt.Color(255, 255, 255));
        add(contactText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 110, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Email ID");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        emailText.setBackground(new java.awt.Color(0, 0, 0));
        emailText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 118, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Date of last donation of Plasma");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        lastDaySymptomsText.setBackground(new java.awt.Color(0, 0, 0));
        lastDaySymptomsText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastDaySymptomsText.setForeground(new java.awt.Color(255, 255, 255));
        lastDaySymptomsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastDaySymptomsTextActionPerformed(evt);
            }
        });
        add(lastDaySymptomsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 114, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Was your COVID-19 diagnosis confirmed by a lab test?");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Currently you do NOT have any symptoms? ");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Has it been at least 14 days since the last day of your symptoms?");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Have you had a follow up test that was negative for COVID-19?");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        nameText.setBackground(new java.awt.Color(0, 0, 0));
        nameText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 118, -1));

        buttonDetails.setText("See Details");
        buttonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetailsActionPerformed(evt);
            }
        });
        add(buttonDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        dobText.setBackground(new java.awt.Color(0, 0, 0));
        dobText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dobText.setForeground(new java.awt.Color(255, 255, 255));
        add(dobText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 111, -1));

        jPanel3.setBackground(new java.awt.Color(23, 35, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Donor Request Handling");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        add(statusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 80, -1));

        jLabel1.setText("Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        lastDonationText.setBackground(new java.awt.Color(0, 0, 0));
        lastDonationText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastDonationText.setForeground(new java.awt.Color(255, 255, 255));
        add(lastDonationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 114, -1));

        labConfirmationText.setBackground(new java.awt.Color(0, 0, 0));
        labConfirmationText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labConfirmationText.setForeground(new java.awt.Color(255, 255, 255));
        add(labConfirmationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 114, -1));

        followUpTestText.setBackground(new java.awt.Color(0, 0, 0));
        followUpTestText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        followUpTestText.setForeground(new java.awt.Color(255, 255, 255));
        followUpTestText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followUpTestTextActionPerformed(evt);
            }
        });
        add(followUpTestText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 114, -1));

        symptomsText.setBackground(new java.awt.Color(0, 0, 0));
        symptomsText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        symptomsText.setForeground(new java.awt.Color(255, 255, 255));
        symptomsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symptomsTextActionPerformed(evt);
            }
        });
        add(symptomsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 114, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApproveActionPerformed
        // TODO add your handling code here:
        if( !statusText.getText().equals("New Request"))
        { JOptionPane.showMessageDialog(null,"Can Not Approve the Request!");
        }
        
        else
        {
        Donor donor = system.getDonorDirectory().addDonor();  
        
        
        
        donor.setDonorID(uidText.getText()); // UID
        donor.setName(nameText.getText()); // Name
        try {
            donor.setDob(new SimpleDateFormat("MM/DD/YYYY").parse(dobText.getText())); // DOB 
            donor.setCovidDiagnosedDate(new SimpleDateFormat("MM/DD/YYYY").parse(diagnosedDateText.getText())); // covidDiagnosedDate
            donor.setCovidCuredDate(new SimpleDateFormat("MM/DD/YYYY").parse(curedText.getText())); // covidCuredDate
            donor.setLastDonationDate(new SimpleDateFormat("MM/DD/YYYY").parse(lastDaySymptomsText.getText())); // lastDonationDate
        } catch (ParseException ex) {
            Logger.getLogger(NewDonorJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        donor.setAge(Integer.parseInt(ageText.getText())); // Age
        donor.setGender(genderText.getText()); // gender
        donor.setBloodGroup(bloodText.getText()); // Blood group
        donor.setStreetAddress(streetText.getText()); // streetAddress
        donor.setCity(cityText.getText()); // city
        donor.setState(stateText.getText()); // state
        donor.setZipCode(Integer.parseInt(zipText.getText())); // zipCode
        donor.setContact(Integer.parseInt(contactText.getText())); // contact
        donor.setEmailID(emailText.getText()); // emailID
        donor.setStatus("Approved"); // status
       /*
               if(userAccount.getEmployee().getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = userAccount.getEmployee().getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        pictureLabel.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
        
        */
        donor.setLabConfirmation(true); //  labConfirmation
        donor.setSymptoms(true); //  symptoms
        donor.setLastDaySymptoms(true); //  lastDaySymptoms
        donor.setFollowUpTest(true); //  followUpTest     
             
        statusText.setText("Government Approved");
        populateRequestTable();
        JOptionPane.showMessageDialog(null,"Request Approved. New Donor added!");
        
        dB4OUtil.storeSystem(system);
        
        }
    }//GEN-LAST:event_buttonApproveActionPerformed

    private void buttonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetailsActionPerformed
        // TODO add your handling code here:
  
        int selectedRow = requestTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table first to View Details!","Warning!",JOptionPane.WARNING_MESSAGE);
        }
        else{
       //display the details 
            populateRequestDetails((DonorRequest) requestTable.getValueAt(selectedRow, 0));
            buttonApprove.setEnabled(true);
            buttonReject.setEnabled(true);
            
            if(Integer.parseInt(ageText.getText()) < 18)
            {
            ageText.setBorder(BorderFactory.createLineBorder(Color.RED));
            ageText.setForeground(Color.red);
            }
            if(labConfirmationText.getText().equals("false"))
            {
            labConfirmationText.setBorder(BorderFactory.createLineBorder(Color.RED));
            labConfirmationText.setForeground(Color.red);
            }
            if(followUpTestText.getText().equals("false"))
            {
            followUpTestText.setBorder(BorderFactory.createLineBorder(Color.RED));
            followUpTestText.setForeground(Color.red);
            }
            if(symptomsText.getText().equals("false"))
            {
            symptomsText.setBorder(BorderFactory.createLineBorder(Color.RED));
            symptomsText.setForeground(Color.red);
            }
            if(lastDaySymptomsText.getText().equals("false"))
            {
            lastDaySymptomsText.setBorder(BorderFactory.createLineBorder(Color.RED));
            lastDaySymptomsText.setForeground(Color.red);
            }
            
            dB4OUtil.storeSystem(system);
            
        }
    }

    private void populateRequestDetails(DonorRequest donorRequest){
            uidText.setText(donorRequest.getDonorID());
            nameText.setText(donorRequest.getName());
            diagnosedDateText.setText(String.valueOf(donorRequest.getCovidDiagnosedDate()));
            dobText.setText(String.valueOf(donorRequest.getDob()));
            curedText.setText(String.valueOf(donorRequest.getCovidCuredDate()));
            lastDaySymptomsText.setText(String.valueOf(donorRequest.getLastDonationDate()));
            ageText.setText(String.valueOf(donorRequest.getAge()));
            genderText.setText(donorRequest.getGender());
            bloodText.setText(donorRequest.getBloodGroup());
            streetText.setText(donorRequest.getStreetAddress());
            cityText.setText(donorRequest.getCity());
            stateText.setText(donorRequest.getState());
            zipText.setText(String.valueOf(donorRequest.getZipCode()));
            contactText.setText(String.valueOf(donorRequest.getContact()));
            emailText.setText(donorRequest.getEmailID());
            statusText.setText(donorRequest.getStatus());
            if(donorRequest.getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = donorRequest.getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        lblProfilePicture.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
            
            System.out.println("VALUES::");
            System.out.println(String.valueOf(donorRequest.isLabConfirmation()));
            System.out.println(String.valueOf(donorRequest.isFollowUpTest()));
            System.out.println(String.valueOf(donorRequest.isSymptoms()));
            System.out.println(String.valueOf(donorRequest.isLastDaySymptoms()));
            labConfirmationText.setText(String.valueOf(donorRequest.isLabConfirmation()));
            followUpTestText.setText(String.valueOf(donorRequest.isFollowUpTest()));
            symptomsText.setText(String.valueOf(donorRequest.isSymptoms()));
            lastDaySymptomsText.setText(String.valueOf(donorRequest.isLastDaySymptoms()));
    
    }//GEN-LAST:event_buttonDetailsActionPerformed

    private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
    
    
    
    private void buttonRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRejectActionPerformed
        // TODO add your handling code here:
       if(!statusText.getText().equals("New Request"))
                  { JOptionPane.showMessageDialog(null,"Can Not Reject the Request!");
        }
       else{
        for(DonorRequest donorRequest: system.getDonorRequestDirectory().getDonorRequestList()){            
        
            if(donorRequest.getName().equals(nameText.getText())){
            statusText.setText("Rejected");
            donorRequest.setStatus("Rejected");
            }}
        populateRequestTable();
        }
       dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_buttonRejectActionPerformed

    private void lastDaySymptomsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastDaySymptomsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastDaySymptomsTextActionPerformed

    private void followUpTestTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followUpTestTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_followUpTestTextActionPerformed

    private void symptomsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptomsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomsTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageText;
    private javax.swing.JTextField bloodText;
    private javax.swing.JButton buttonApprove;
    private javax.swing.JButton buttonDetails;
    private javax.swing.JButton buttonReject;
    private javax.swing.JTextField cityText;
    private javax.swing.JTextField contactText;
    private javax.swing.JTextField curedText;
    private javax.swing.JTextField diagnosedDateText;
    private javax.swing.JTextField dobText;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField followUpTestText;
    private javax.swing.JTextField genderText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField labConfirmationText;
    private javax.swing.JTextField lastDaySymptomsText;
    private javax.swing.JTextField lastDonationText;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JTextField nameText;
    private javax.swing.JTable requestTable;
    private javax.swing.JTextField stateText;
    private javax.swing.JTextField statusText;
    private javax.swing.JTextField streetText;
    private javax.swing.JTextField symptomsText;
    private javax.swing.JTextField uidText;
    private javax.swing.JTextField zipText;
    // End of variables declaration//GEN-END:variables
}
