/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PlasmaBankCoordinatorRole;

import Business.BloodGroup.BloodGroup;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PlasmaBankOrganization;
import Business.Organization.SystemCoordinatorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akshay
 */
public class PlasmaRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlasmaCountJPanel
     */
    private UserAccount userAccount;
    private PlasmaBankOrganization plasmaorganization;
    private Enterprise enterprise;
    private Network network;
    
    public PlasmaRequestJPanel(UserAccount userAccount, PlasmaBankOrganization plasmaorganization, Enterprise enterprise, Network network) {
        initComponents();
        this.userAccount = userAccount;
        this.plasmaorganization = plasmaorganization;
        this.enterprise = enterprise;
        this.network = network;
        
        populateTextFields();
        populatePlasmaCoordinatorTable();
    }

   

    public void populateTextFields(){
        
        txtAnegative.setText(String.valueOf(BloodGroup.getaNegative()));
        txtApositive.setText(String.valueOf(BloodGroup.getaPositive()));
        txtABpositive.setText(String.valueOf(BloodGroup.getAbPositive()));
        txtABnegative.setText(String.valueOf(BloodGroup.getAbNegative()));
        txtOpositive.setText(String.valueOf(BloodGroup.getoPositive()));
        txtOnegative.setText(String.valueOf(BloodGroup.getoNegative()));
        txtBpositive.setText(String.valueOf(BloodGroup.getbPositive()));
        txtBnegative.setText(String.valueOf(BloodGroup.getbNegative()));
        
    }
    
    public void populatePlasmaCoordinatorTable(){
        DefaultTableModel model = (DefaultTableModel)tblPlasmaCoordinator.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getPatient();
            row[2] = request.getPatient().getName();
            row[3] = request.getPatient().getContact();
            row[4] = request.getPatient().getBloodGroup();
            row[5] = request.getStatus();
             
            model.addRow(row);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApositive = new javax.swing.JTextField();
        btnApprove = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtAnegative = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtOpositive = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBnegative = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBpositive = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtOnegative = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtABpositive = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtABnegative = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnOnHold = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlasmaCoordinator = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(73, 128, 242));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("List of Plasma Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 77, -1, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 247, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Blood Group Category");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 265, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Available Blood Groups");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 265, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("A+");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 304, -1, 16));

        txtApositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApositiveActionPerformed(evt);
            }
        });
        add(txtApositive, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 301, 99, -1));

        btnApprove.setText("Approve Request");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 496, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("A-");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 303, -1, -1));
        add(txtAnegative, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 300, 79, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("O+");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 366, -1, -1));
        add(txtOpositive, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 363, 99, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("O-");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));
        add(txtBnegative, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 74, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("B +");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 25, -1));
        add(txtBpositive, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 99, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("B-");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));
        add(txtOnegative, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 72, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("AB+");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 406, -1, -1));
        add(txtABpositive, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 403, 99, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("AB-");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 406, -1, -1));
        add(txtABnegative, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 403, 64, -1));

        jLabel14.setText("Request to other Network's Plasma Bank to help in case of Unavailability  ");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 601, 442, -1));

        btnOnHold.setText("On Hold");
        add(btnOnHold, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 496, -1, -1));

        tblPlasmaCoordinator.setBackground(new java.awt.Color(0, 0, 0));
        tblPlasmaCoordinator.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblPlasmaCoordinator.setForeground(new java.awt.Color(255, 255, 255));
        tblPlasmaCoordinator.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Patient ID", "Patient Name", "Contact No", "Blood Group", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblPlasmaCoordinator);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 750, 111));

        jPanel3.setBackground(new java.awt.Color(23, 35, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Plasma Bank");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtApositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApositiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApositiveActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblPlasmaCoordinator.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        
        WorkRequest request = (WorkRequest)tblPlasmaCoordinator.getValueAt(selectedRow, 0);
        //request.setReceiver(userAccount);
        request.setStatus("PlasmaBank Approved. Passing to System Coordinator");
        //request.setUserAccount(userAccount);
        //userAccount.getWorkQueue().getWorkRequestList().add(request);
        populatePlasmaCoordinatorTable();
        
        
        Enterprise ent = null;
        Organization org = null;
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getEnterpriseType().toString().equals("Hospital")) {
            
                ent = enterprise;
                System.out.println(enterprise);
                break;
            }
        }
        
        
       
        for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
            if(organization instanceof SystemCoordinatorOrganization) {
                org = organization;
                break;
            }
        }
        
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            System.out.println(org.getName()+"Orgcheck");
            
            //user.addUserRequest(request);
            
            
        } else {
        
         JOptionPane.showMessageDialog(null, "No organization present", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnApproveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnOnHold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPlasmaCoordinator;
    private javax.swing.JTextField txtABnegative;
    private javax.swing.JTextField txtABpositive;
    private javax.swing.JTextField txtAnegative;
    private javax.swing.JTextField txtApositive;
    private javax.swing.JTextField txtBnegative;
    private javax.swing.JTextField txtBpositive;
    private javax.swing.JTextField txtOnegative;
    private javax.swing.JTextField txtOpositive;
    // End of variables declaration//GEN-END:variables
}
