/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PathologistRole;

import Business.BloodGroup.BloodGroup;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PathologistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akshay
 */
public class ManagePathologistRequests extends javax.swing.JPanel {

    /**
     * Creates new form DonorListJPanel
     */
    private EcoSystem system;
    private UserAccount userAccount;
    private PathologistOrganization pathoorganization;
    private Enterprise enterprise;
    
    public ManagePathologistRequests(EcoSystem system, UserAccount userAccount, PathologistOrganization pathoorganization, Enterprise enterprise) {
        initComponents();
        this.pathoorganization = pathoorganization;
        this.enterprise = enterprise;
        this.system = system;
        this.userAccount = userAccount;
        populateOrganizationDonorTable();
        populatePathologistDonorTable();
    }
    
    
    public void populateOrganizationDonorTable(){
        DefaultTableModel model = (DefaultTableModel)tblOrganisationDonors.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : pathoorganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getSummary();
            row[2] = request.getDonor().getName();
            row[3] = request.getDonor().getName();
            row[4] = request.getDonor().getContact();
            row[5] = request.getStatus();
            
            model.addRow(row);
        }
    }
    
    public void populatePathologistDonorTable(){
        DefaultTableModel model = (DefaultTableModel)tblPathologistDonors.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getDonor().getName();
            row[2] = request.getDonor().getName();
            row[3] = request.getDonor().getContact();
            row[4] = request.getUserAccount().getUsername();
            row[5] = request.getStatus();
             
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganisationDonors = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAssignPathologist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPathologistDonors = new javax.swing.JTable();
        buttonAddPlasma = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        txtBloodGroup = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(73, 128, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrganisationDonors.setBackground(new java.awt.Color(0, 0, 0));
        tblOrganisationDonors.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblOrganisationDonors.setForeground(new java.awt.Color(255, 255, 255));
        tblOrganisationDonors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Summary", "Donor UID", "Donor Name", "Contact", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganisationDonors);
        if (tblOrganisationDonors.getColumnModel().getColumnCount() > 0) {
            tblOrganisationDonors.getColumnModel().getColumn(0).setResizable(false);
            tblOrganisationDonors.getColumnModel().getColumn(1).setResizable(false);
            tblOrganisationDonors.getColumnModel().getColumn(2).setResizable(false);
            tblOrganisationDonors.getColumnModel().getColumn(3).setResizable(false);
            tblOrganisationDonors.getColumnModel().getColumn(4).setResizable(false);
            tblOrganisationDonors.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 123, 750, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List of people Who Wish to Be Donors");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 81, 511, -1));

        btnAssignPathologist.setText("Assign To Me");
        btnAssignPathologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignPathologistActionPerformed(evt);
            }
        });
        add(btnAssignPathologist, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 254, -1, -1));

        tblPathologistDonors.setBackground(new java.awt.Color(0, 0, 0));
        tblPathologistDonors.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblPathologistDonors.setForeground(new java.awt.Color(255, 255, 255));
        tblPathologistDonors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Donor UID", "Donor Name", "Contact", "Assigned to", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPathologistDonors);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 313, 750, 102));

        buttonAddPlasma.setText("Add Plasma to Bank");
        buttonAddPlasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPlasmaActionPerformed(evt);
            }
        });
        add(buttonAddPlasma, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 660, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Blood Pressure Check");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, 34));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pulse Check");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 471, -1, -1));

        jButton1.setText("Plasma donated by the donor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Health check");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 471, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tests on Plasma for other infections");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 608, -1, -1));

        jLabel7.setText("Date of Last Donation of Plasma gets updated");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 548, -1, -1));

        jButton3.setText("Or discard the donated plasma");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 660, -1, -1));

        jLabel8.setText("On adding in Bank - increase the availability Count in the same Network area");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 698, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 465, 20, -1));

        jCheckBox2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setOpaque(false);
        add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 20, 20));

        jCheckBox3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setOpaque(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 20, 20));

        txtBloodGroup.setBackground(new java.awt.Color(0, 0, 0));
        txtBloodGroup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBloodGroup.setForeground(new java.awt.Color(255, 255, 255));
        add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 605, 121, -1));

        jPanel3.setBackground(new java.awt.Color(23, 35, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Manage Donor Request - Pathologist ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignPathologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignPathologistActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrganisationDonors.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        WorkRequest request = (WorkRequest)tblOrganisationDonors.getValueAt(selectedRow, 0);
        //request.setReceiver(userAccount);
        request.setStatus("Assign to Pathologist" + userAccount.getUsername());
        request.setUserAccount(userAccount);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        populateOrganizationDonorTable();
        populatePathologistDonorTable();
    }//GEN-LAST:event_btnAssignPathologistActionPerformed

    private void buttonAddPlasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPlasmaActionPerformed
        // TODO add your handling code here:
        
          BloodGroup bloodGroup = new BloodGroup(txtBloodGroup.getText());
    }//GEN-LAST:event_buttonAddPlasmaActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignPathologist;
    private javax.swing.JButton buttonAddPlasma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrganisationDonors;
    private javax.swing.JTable tblPathologistDonors;
    private javax.swing.JTextField txtBloodGroup;
    // End of variables declaration//GEN-END:variables
}
